### PR TITLE
closes #52; trimming all package names

### LINKED ISSUE #52: Trailing spaces are not trimmed if provided value is author
I guess the title is descriptive enough.
I could pick this up if you want.

### PR DESCRIPTION
**Pull request by e-e**
Pretty straightforward, just trimming package names before they are concatenated to the ```packageNameQueryString```

### CODE REVIEW

**Comment by pvorb** [comment]
Not accepting as there is only one valid changed line and everything else is just destroying my code format.

**Comment by e-e** [comment]
A little dramatic, don't you think?

**Comment by pvorb** [comment]
No, I think it's appropriate. Simply don't auto-format if you don't have the correct settings.

**Comment by e-e** [comment]
I apologize. I misread your first comment as "destroying my code." missed the "format" part. The formatting changes were unintentional.

**Pull request closed without merging**
